---
title: "CV"
description: "Experience, technical skills and publications across ten years of neuroscience research."
toc: true
---

[<i class="bi bi-file-earmark-arrow-down"></i> Download CV (PDF)](assets/cv.pdf){.btn .btn-outline-secondary .btn-sm .rounded-pill .cv-button target="_blank"}

[Last updated: 2026-07-21]{.cv-updated}

## Research experience

::: {.pub-timeline}
::: {.pub-year}
August 2023 - June 2026
:::
::: {.pub-entries}
::: {.pub-entry}
**Postdoctoral Research Scientist**

[Reiser Lab](https://www.janelia.org/lab/reiser-lab), Howard Hughes Medical Institute (HHMI) Janelia Research Campus
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
September 2016 - May 2023
:::
::: {.pub-entries}
::: {.pub-entry}
**PhD Student**

[Joesch Lab](https://ista.ac.at/en/research/josch-group/), Insitute of Science and Technology Austria (ISTA)
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
June 2016 - August 2016
:::
::: {.pub-entries}
::: {.pub-entry}
**Graduate Summer Intern**

[Hippenmeyer Lab](https://ist.ac.at/en/research/hippenmeyer-group/), Insitute of Science and Technology Austria (ISTA)
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
September 2015 - June 2016
:::
::: {.pub-entries}
::: {.pub-entry}
**Master's Student**

with [Dr Conor McCann](https://www.ucl.ac.uk/population-health-sciences/child-health/research/stem-cells-regenerative-medicine/gut-development-and-repair-group) within the Burns Lab, UCL Institute of Child Health, London 
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
February 2015 - June 2015
:::
::: {.pub-entries}
::: {.pub-entry}
**Undergraduate research placement**

[Young Lab](https://pursuit.unimelb.edu.au/individuals/professor-heather-young), The University of Melbourne, Australia
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
September 2014 - November 2014
:::
::: {.pub-entries}
::: {.pub-entry}
**Undergraduate lab experience**

with Dr Joanne Britto in the Tan Lab, The Florey Institute, Melbourne, Australia
:::
:::
:::

## Education

::: {.pub-timeline}
::: {.pub-year}
September 2015 - May 2016
:::
::: {.pub-entries}
::: {.pub-entry}
**Natural Sciences MSc** (First Class Honours)

*Neuroscience*

Univeristy College London (UCL)
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
September 2012 - May 2015
:::
::: {.pub-entries}
::: {.pub-entry}
**Natural Sciences BSc** (First Class Honours)

*Organic chemistry & Biomedical sciences*

Univeristy College London (UCL)
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
July 2014 - July 2015
:::
::: {.pub-entries}
::: {.pub-entry}
**Study Abroad** (First Class Honours & Dean's List Award for outstanding grades)

The University of Melbourne, Australia
:::
:::
:::

## Publications

::: {.pub-timeline}
::: {.pub-year}
2026
:::
::: {.pub-entries}
::: {.pub-entry}
**[Sexual dimorphism in the complete connectome of the Drosophila male central nervous system](https://doi.org/10.1101/2025.10.09.680999)**


Berg, S., ... Burnett, L.E., et al. *BioRXiv*. 2026.
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
2025
:::
::: {.pub-entries}
::: {.pub-entry}
**[Connectome-driven neural inventory of a complete visual system](https://doi.org/10.1038/s41586-025-08746-0)**


Nern, A., Loesche, F., Takemura, Sy., Burnett, L., et al. *Nature*. 2025.
:::
:::
:::


::: {.pub-timeline}
::: {.pub-year}
2024
:::
::: {.pub-entries}
::: {.pub-entry}
**[Shared behavioural impairments in visual perception and place avoidance across different autism models are driven by periaqueductal grey hypoexcitability in Setd5 haploinsufficient mice](https://doi.org/10.1371/journal.pbio.3002668)**

Burnett, L.E., Koppensteiner, P., Symonova, O., Masson, T., Vega-Zuniga, T., Contreras, X., Rülicke, T., Shigemoto, R., Novarino, G., Joesch, M. *PLoS Biology*. 2024.

:::
:::
:::


::: {.pub-timeline}
::: {.pub-year}
2019
:::
::: {.pub-entries}
::: {.pub-entry}
**[Role of JNK, MEK and adenylyl cyclase signalling in speed and directionality of enteric neural crest-derived cells](https://doi.org/10.1016/j.ydbio.2019.07.007)**

Hao, M.M., ... Burnett, L.E. et. al. *Developmental Biology*. 2019.
:::
:::
:::

::: {.pub-timeline}
::: {.pub-year}
2017
:::
::: {.pub-entries}
::: {.pub-entry}
**[Transplantation of enteric nervous system stem cells rescues nitric oxide synthase deficient mouse colon](https://doi.org/10.1038/ncomms15937)**

McCann C.J., ... Burnett, L.E. et. al. *Nature Communications*. 2017.
:::
:::
:::


::: {.pub-timeline}
::: {.pub-year}
2017
:::
::: {.pub-entries}
::: {.pub-entry}
**[Mosaic Analysis with Double Markers Reveals Distinct Sequential Functions of Lgl1 in Neural Stem Cells](https://doi.org/10.1016/j.neuron.2017.04.012)**

Beattie, R., Postiglione, M.P., Burnett, L.E. et. al. *Neuron*. 2017.
:::
:::
:::



## Submitted publications

::: {.pub-timeline}
::: {.pub-year}
2026
:::
::: {.pub-entries}
::: {.pub-entry}
*Localization of an IgSF-GABA receptor complex sculpts directional selectivity*
Sanfilippo, P.,  ... Burnett, L.E., et al. 
:::
:::
:::



## PhD Thesis

::: {.pub-timeline}
::: {.pub-year}
2023
:::
::: {.pub-entries}
::: {.pub-entry}
**[To flee, or not to flee? Using innate defensive behaviours to investigate rapid perceptual decision-making through subcortical circuits in mouse models of autism.](https://research-explorer.ista.ac.at/download/12716/12718/Burnett_Thesis_2023_pdfA.pdf)**

Burnett, L.E. 2023.
:::
:::
:::
