#!/usr/bin/env python3
"""Generate `_project-nav.html`: previous / next links for the project pages.

The order is read from each project's `priority` frontmatter field — the same
field that orders the cards in the grid — so the two can never disagree. Run
this after adding a project or changing a priority; the output is committed.

`_project-nav.html` is pulled in through `include-after-body` in `_quarto.yml`,
and injects the nav at the foot of the page it recognises. Doing it in the
browser rather than at render time is what keeps the ordering in one place: a
Quarto include is the same text on every page, so per-page prev/next links
would otherwise need a separate include per project.

Usage
-----
    python3 scripts/build-project-nav.py          # write _project-nav.html
    python3 scripts/build-project-nav.py --check  # verify it is up to date
"""

import argparse
import glob
import json
import os
import re
import sys

PROJECT_GLOB = "projects/*.qmd"
EXCLUDE = {"index.qmd"}
OUT = "_project-nav.html"


def frontmatter(path):
    """Return the frontmatter block of a .qmd as a string, or '' if absent."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    return m.group(1) if m else ""


def collect():
    """Ordered list of {slug, title, priority} for every project page."""
    items = []
    for path in sorted(glob.glob(PROJECT_GLOB)):
        if os.path.basename(path) in EXCLUDE:
            continue
        fm = frontmatter(path)
        title = re.search(r'^title:\s*"?(.*?)"?\s*$', fm, re.M)
        priority = re.search(r"^priority:\s*(\d+)", fm, re.M)
        if not title:
            print(f"  [!] {path} has no title — skipped")
            continue
        if not priority:
            print(f"  [!] {path} has no priority — skipped (it would have no place in the order)")
            continue
        items.append({
            "slug": os.path.basename(path)[:-4],
            # Titles frequently end in a full stop, which reads oddly on a button.
            "title": title.group(1).strip().rstrip("."),
            "priority": int(priority.group(1)),
        })
    items.sort(key=lambda i: i["priority"])
    return items


def render(items):
    order = [{"slug": i["slug"], "title": i["title"]} for i in items]
    return f"""<!-- Generated by scripts/build-project-nav.py — do not edit by hand.
     Order comes from the `priority` frontmatter of each project page. -->
<script>
(function () {{
  var ORDER = {json.dumps(order, indent=2, ensure_ascii=False)};

  var match = window.location.pathname.match(/\\/projects\\/([^\\/]+?)(?:\\.html)?$/);
  if (!match) return;
  var i = ORDER.findIndex(function (p) {{ return p.slug === match[1]; }});
  if (i === -1) return;                      // projects/index, or an unlisted page

  var main = document.querySelector('main');
  if (!main) return;

  function link(project, rel) {{
    var a = document.createElement('a');
    a.className = 'project-nav-link project-nav-link--' + rel;
    a.href = project.slug + '.html';
    a.innerHTML = '<span class="project-nav-rel">' +
                  (rel === 'prev' ? '&larr; Previous' : 'Next &rarr;') +
                  '</span><span class="project-nav-title"></span>';
    // Titles are author-supplied: set them as text, never as markup.
    a.querySelector('.project-nav-title').textContent = project.title;
    return a;
  }}

  var nav = document.createElement('nav');
  nav.className = 'project-nav';
  nav.setAttribute('aria-label', 'Project navigation');

  if (i > 0) nav.appendChild(link(ORDER[i - 1], 'prev'));

  var all = document.createElement('a');
  all.className = 'project-nav-all';
  all.href = 'index.html';
  all.textContent = 'All projects';
  nav.appendChild(all);

  if (i < ORDER.length - 1) nav.appendChild(link(ORDER[i + 1], 'next'));

  main.appendChild(nav);
}})();
</script>
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__.split("Usage\n-----\n", 1)[1])
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed file is stale")
    args = ap.parse_args()

    items = collect()
    if not items:
        sys.exit("No project pages found — run this from the repository root.")
    html = render(items)

    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != html:
            print(f"{OUT} is out of date — run: python3 {sys.argv[0]}")
            return 1
        print(f"{OUT} is up to date ({len(items)} projects).")
        return 0

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)
    print(f"wrote {OUT} — {len(items)} projects in priority order:")
    for i in items:
        print(f"  {i['priority']:>2}  {i['slug']:26} {i['title']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
